name: shawnee
author: shawnee
baseurl: http://www.shawnee.life
description: a place for shawnee
github: http://www.github.com/shaawnee
twitter: http://www.twitter.com/_partybarge
facebook: http://www.facebook.com/shawneepotts
linkedin: https://www.linkedin.com/pub/shawnee-potts/99/781/504
email: potts.shawnee[at]gmail.com
location: 40°40'5"N   73°56'41"W
#disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
